#!/bin/bash

nsimdrv \
    -on nsim_isa_enable_timer_0             \
    -on nsim_isa_enable_timer_1             \
    -off invalid_instruction_interrupt      \
    -off memory_exception_interrupt         \
    -prop=nsim_emt=1                        \
    -p nsim_isa_family=av3hs                \
    -p nsim_isa_div_rem_option=2            \
    -p nsim_isa_mpy_option=9                \
    -p nsim_isa_mpy64=1                     \
    -p nsim_isa_div64_option=1              \
    -p nsim_isa_unaligned_option=1          \
    -p nsim_isa_atomic_option=1             \
    -p nsim_isa_shift_option=0              \
    -p nsim_isa_bitscan_option=0            \
    -p nsim_isa_ll64_option=1               \
    "$@"
